# Generated by Django 5.0.4 on 2024-06-07 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='accounts.userprofile', to_field='user'),
        ),
    ]
