# Generated by Django 4.1 on 2024-06-07 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_friendship_from_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendship",
            unique_together={("from_user", "to_user")},
        ),
    ]
